apiVersion: v1
kind: Service
metadata:
  name: kubernetes-poc-service
spec:
  selector:
    app: kubernetes-poc
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-poc
spec:
  selector:
    matchLabels:
      app: kubernetes-poc
  replicas: 4
  template:
    metadata:
      labels:
        app: kubernetes-poc
    spec:
      containers:
      - name: kubernetes-poc
        image: kubernetes-poc:latest
        ports:
        - containerPort: 8000